services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      # Optional: Configure environment variables for Grafana
      - GF_LOG_LEVEL=info
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=[replace with a password of your choosing]

volumes:
  grafana-storage: {}
